[default]
        accelerator='cuda'
        pretrained_model_name_or_path= 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext'
        british_spellings_json_path='./british_spellings.json'
        prediction_model_name_or_path='/path/to/the/prediction/model'
        allen_nli_model='pair-classification-roberta-mnli'
        [default.config_param]
                num_workers=8
                val_check_interval=0.25
                test_split=0.2
        [default.path]
		            data_path='/path/to/the/csv/train'
		            checkpoint_path='/path/to/store/the/model'
		            logging_dir='/path/to/tensorboard/logging_dir'
                prediction_path='/path/to/store/predicted/data'
	      [default.hyperparameters]
                task_name='SelfSupervisedMaskingTask'
                seed=42
		            verb_frequency_threshold=11
                learning_rate=2e-5
                adam_epsilon=1e-8
                warmup_steps=0
                weight_decay=0
                train_batch_size=32
                eval_batch_size=64
                nli_model_bath_size=32
                test_count=500
                max_seq_lengt=256
                top_k=20
                max_epochs=3
[test]
        accelerator='cpu'
        prediction_model_path='None'
        [test.config_param]
                num_workers=0
                val_check_interval=0.25
                test_split=0.2
        [test.path]
                data_path='./tests/test_docs/test_data.csv'
                prediction_path='./tmp/'
                checkpoint_path='./tmp/checkpoint_path/'
                logging_dir='./tmp/logging_dir'
        [test.hyperparameters]
                task_name='SelfSupervisedMaskingTask'
                seed=42
		            verb_frequency_threshold=2
                learning_rate=2e-5
                adam_epsilon=1e-8
                warmup_steps=0
                weight_decay=0
                train_batch_size=32
                eval_batch_size=64
                nli_model_batch_size=32
                test_count=5000
                max_seq_length=256
                top_k=20
                max_epochs=1
